services:
  yt-fabric-ui:
    build: .
    image: yt-fabric-ui:1.0.6
    network_mode: "host"
    volumes:
      - ./data:/app/data
      - ./.config/fabric:/home/fabric/.config/fabric
    environment:
      - PORT=8090
