services:
  yt-fabric-ui:
    build: .
    image: yt-fabric-ui:1.0.5
    ports:
      - "8090:8090"
    volumes:
      - ./data:/app/data
      - ./.config/fabric:/home/fabric/.config/fabric
    environment:
      - PORT=8090
